/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nnrgqyoczrwcozmvkbmi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ucmdxeW9jenJ3Y296bXZrYm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2NjkwNTAsImV4cCI6MjA4MzI0NTA1MH0.pT4WY-X6OwHR-5X9xbRawNXN7TE1reigmz0Nz80NhAM"